### ISSUE TITLE
I can merge one profile's data into another profile's data. I can then delete the empty profile.

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/earwig#367] opened 2019-06-14 15:55 UTC

**Comment by RamyAlshurafa** [comment] 2019-07-04 09:32
Hey @theharrisonmoore 
regarding this issue `merging two profiles`, what we were discussing is to make 2 selects dropdown lists of the profiles, one for the profile to be merged and the second for the profile to merge into, with submit button
that will transfer the reviews on the profile that merged to the profile we want to merge into.
so the profile's data that we will merge into will not change. if you need to update the profile data, you can do that from editing profiles page on the admin dashboard.
what do you think?

**Comment by theharrisonmoore** [comment] 2019-07-04 10:41
@ramy@yallacooperative.com <ramy@yallacooperative.com> Hi, I'm sorry, I
don't quite understand what you mean.

Are you saying that the data from one profile cannot be merged into another
without doing it manually?

-

Best,
Harrison Moore

**Comment by RamyAlshurafa** [comment] 2019-07-04 11:42
@theharrisonmoore 
sorry for confusing, can you explain to me what you expect from this issue?
ignore the prev comment

**Comment by theharrisonmoore** [comment] 2019-07-04 12:03
@ramy@yallacooperative.com <ramy@yallacooperative.com> Sure,

Let's say user 1 searches for *Profit People Payroll*, finds it in the
list, and gives a review.

Next, let's say user 2 searches for the same company but types *PPP.* Profit
People Payroll doesn't appear in the list, so he creates a new profile for
PPP.

Next, let's say 50 users subsequently give reviews about PPP while another
50 users give reviews about Profit People Payroll. The problem is that they
are the same company. So, Admin needs the ability to merge the review data
from PPP into Profit People Payroll, and to then delete PPP.

Does that make sense?

-

Best,
Harrison Moore

**Comment by RamyAlshurafa** [comment] 2019-07-04 12:07
cool, Thanks :+1:

**Closed** 2019-07-08 08:40 UTC
Labels: admin, priority-4
